import { useState } from 'react';
import { Routes, Route } from 'react-router-dom';
import { BodyWrapper } from './StyledModule';
import Template from './components/Template';

const Body = () => {
	const [pageData] = useState({
		dashboard: [{
			rowStart: 1,
			columnStart: 1,
			rowEnd: 7,
			columnEnd: 3
		}, {
			rowStart: 1,
			columnStart: 3,
			rowEnd: 3,
			columnEnd: 5
		}, {
			rowStart: 1,
			columnStart: 5,
			rowEnd: 3,
			columnEnd: 7
		}, {
			rowStart: 3,
			columnStart: 3,
			rowEnd: 5,
			columnEnd: 5
		}, {
			rowStart: 3,
			columnStart: 5,
			rowEnd: 5,
			columnEnd: 7
		}, {
			rowStart: 5,
			columnStart: 3,
			rowEnd: 7,
			columnEnd: 5
		}, {
			rowStart: 5,
			columnStart: 5,
			rowEnd: 7,
			columnEnd: 7
		}],
		projects: [{
			rowStart: 1,
			columnStart: 1,
			rowEnd: 4,
			columnEnd: 3
		}, {
			rowStart: 1,
			columnStart: 3,
			rowEnd: 2,
			columnEnd: 5
		}, {
			rowStart: 2,
			columnStart: 3,
			rowEnd: 4,
			columnEnd: 5
		}, {
			rowStart: 1,
			columnStart: 5,
			rowEnd: 4,
			columnEnd: 6
		}, {
			rowStart: 1,
			columnStart: 6,
			rowEnd: 4,
			columnEnd: 7
		}, {
			rowStart: 4,
			columnStart: 1,
			rowEnd: 7,
			columnEnd: 2
		}, {
			rowStart: 4,
			columnStart: 2,
			rowEnd: 7,
			columnEnd: 3
		}, {
			rowStart: 4,
			columnStart: 3,
			rowEnd: 7,
			columnEnd: 5
		}, {
			rowStart: 4,
			columnStart: 5,
			rowEnd: 6,
			columnEnd: 7
		}, {
			rowStart: 6,
			columnStart: 5,
			rowEnd: 7,
			columnEnd: 7
		}],
		team: [{
			rowStart: 1,
			columnStart: 1,
			rowEnd: 4,
			columnEnd: 3
		}, {
			rowStart: 4,
			columnStart: 1,
			rowEnd: 7,
			columnEnd: 3
		}, {
			rowStart: 1,
			columnStart: 3,
			rowEnd: 4,
			columnEnd: 5
		}, {
			rowStart: 4,
			columnStart: 3,
			rowEnd: 7,
			columnEnd: 5
		}, {
			rowStart: 1,
			columnStart: 5,
			rowEnd: 4,
			columnEnd: 7
		}, {
			rowStart: 4,
			columnStart: 5,
			rowEnd: 7,
			columnEnd: 7
		}],
		reports: [{
			rowStart: 1,
			columnStart: 1,
			rowEnd: 2,
			columnEnd: 3
		}, {
			rowStart: 2,
			columnStart: 1,
			rowEnd: 4,
			columnEnd: 3
		}, {
			rowStart: 1,
			columnStart: 3,
			rowEnd: 4,
			columnEnd: 5
		}, {
			rowStart: 1,
			columnStart: 5,
			rowEnd: 4,
			columnEnd: 6
		}, {
			rowStart: 1,
			columnStart: 6,
			rowEnd: 4,
			columnEnd: 7
		}, {
			rowStart: 4,
			columnStart: 1,
			rowEnd: 7,
			columnEnd: 3
		}, {
			rowStart: 4,
			columnStart: 3,
			rowEnd: 7,
			columnEnd: 4
		}, {
			rowStart: 4,
			columnStart: 4,
			rowEnd: 7,
			columnEnd: 5
		}, {
			rowStart: 4,
			columnStart: 5,
			rowEnd: 6,
			columnEnd: 7
		}, {
			rowStart: 6,
			columnStart: 5,
			rowEnd: 7,
			columnEnd: 7
		}],
		documents: [{
			rowStart: 1,
			columnStart: 1,
			rowEnd: 3,
			columnEnd: 3
		}, {
			rowStart: 1,
			columnStart: 3,
			rowEnd: 3,
			columnEnd: 5
		}, {
			rowStart: 1,
			columnStart: 5,
			rowEnd: 3,
			columnEnd: 7
		}, {
			rowStart: 3,
			columnStart: 1,
			rowEnd: 5,
			columnEnd: 3
		}, {
			rowStart: 3,
			columnStart: 3,
			rowEnd: 5,
			columnEnd: 5
		}, {
			rowStart: 3,
			columnStart: 5,
			rowEnd: 5,
			columnEnd: 7
		}, {
			rowStart: 5,
			columnStart: 1,
			rowEnd: 7,
			columnEnd: 3
		}, {
			rowStart: 5,
			columnStart: 3,
			rowEnd: 7,
			columnEnd: 5
		}, {
			rowStart: 5,
			columnStart: 5,
			rowEnd: 7,
			columnEnd: 7
		}],
		calendar: [{
			rowStart: 1,
			columnStart: 1,
			rowEnd: 3,
			columnEnd: 2
		}, {
			rowStart: 1,
			columnStart: 2,
			rowEnd: 3,
			columnEnd: 3
		}, {
			rowStart: 1,
			columnStart: 3,
			rowEnd: 3,
			columnEnd: 4
		}, {
			rowStart: 1,
			columnStart: 4,
			rowEnd: 3,
			columnEnd: 5
		}, {
			rowStart: 1,
			columnStart: 5,
			rowEnd: 3,
			columnEnd: 6
		}, {
			rowStart: 1,
			columnStart: 6,
			rowEnd: 3,
			columnEnd: 7
		}, {
			rowStart: 3,
			columnStart: 1,
			rowEnd: 5,
			columnEnd: 2
		}, {
			rowStart: 3,
			columnStart: 2,
			rowEnd: 5,
			columnEnd: 3
		}, {
			rowStart: 3,
			columnStart: 3,
			rowEnd: 5,
			columnEnd: 4
		}, {
			rowStart: 3,
			columnStart: 4,
			rowEnd: 5,
			columnEnd: 5
		}, {
			rowStart: 3,
			columnStart: 5,
			rowEnd: 5,
			columnEnd: 6
		}, {
			rowStart: 3,
			columnStart: 6,
			rowEnd: 5,
			columnEnd: 7
		}, {
			rowStart: 5,
			columnStart: 1,
			rowEnd: 7,
			columnEnd: 2
		}, {
			rowStart: 5,
			columnStart: 2,
			rowEnd: 7,
			columnEnd: 3
		}, {
			rowStart: 5,
			columnStart: 3,
			rowEnd: 7,
			columnEnd: 4
		}, {
			rowStart: 5,
			columnStart: 4,
			rowEnd: 7,
			columnEnd: 5
		}, {
			rowStart: 5,
			columnStart: 5,
			rowEnd: 7,
			columnEnd: 6
		}, {
			rowStart: 5,
			columnStart: 6,
			rowEnd: 7,
			columnEnd: 7
		}]
	})
	return(
		<BodyWrapper>
			<Routes>
				<Route path="react-navigation" element={<Template data={pageData.dashboard} name="Dashboard" />} />
				<Route path="react-navigation/projects" element={<Template data={pageData.projects} name="Projects" />} />
				<Route path="react-navigation/team" element={<Template data={pageData.team} name="Team" />} />
				<Route path="react-navigation/calendar" element={<Template data={pageData.calendar} name="Calendar" />} />
				<Route path="react-navigation/documents" element={<Template data={pageData.documents} name="Documents" />} />
				<Route path="react-navigation/reports" element={<Template data={pageData.reports} name="Reports" />} />
			</Routes>
		</BodyWrapper>
	)
}

export default Body